### ISSUE TITLE
"system:serviceaccount:default:default" cannot list resource "pods" in API group ""

### ISSUE THREAD

**Issue by survivant** [markyjackson-taulia/jenkinsci-on-kubernetes#46]
context : 

I have a cluster created on premise
````
vagrant@k8s-master:~/openebs-jenkins$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
vagrant@k8s-master:~/openebs-jenkins$
````

When I try to install the inboud-agent, I got this error

````
jenkins  Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" in the namespace "default".
````

I found a solution here
````
https://issues.jenkins.io/browse/JENKINS-55788
````

I had to run this command : 
````
kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts
````

I'm not sure if it's the right way to fix the issue, if you think about production.  

Maybe you could add that to the readme.md  if someone else have the issue, and also.. what is the <strike>best</strike> right way to do that

thanks

**Comment by markyjackson-taulia** [comment]
@survivant Thank you for your question. 
After reviewing what you are describing it seems there could be a possibility that the RBAC.yaml was not used, it can be found [here](https://github.com/markyjackson-taulia/jenkinsci-on-kubernetes/blob/master/jenkins-admin-rbac.yaml#L2-L6).
This file allows Jenkins to interact with the Kubernetes cluster. The error you are getting (`jenkins  Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" in the namespace "default".`) leads me to believe this is the case. Also, ensure that you are setting up your Jenkins in the namespace `jenkins` as noted in the youtube video. Judging from the error, you are setting this up in the `default` namesspace and the RBAC I am using defines a namespace of `jenkins`. Give those a try and let me know. 

I will leave this issue open for 24 hours to see if there is anything extra you may want to add but I beleive what I noted above will resolve your issue as it pertains to this repo..

Thanks kindly again :-)

**Comment by survivant** [comment]
I find out that I had 2 jenkins running.. a old one in jenkins namespace.. but the right one was running in default namespace.  The one that is working is in the default.  but I think because I used default as namespace, I had to run the command specified.

now I have this error
````
Feb 07, 2021 3:45:11 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: http://192.168.50.8:30726/ provided port:50000 is not reachable
java.io.IOException: http://192.168.50.8:30726/ provided port:50000 is not reachable
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:314)
        at hudson.remoting.Engine.innerRun(Engine.java:693)
        at hudson.remoting.Engine.run(Engine.java:518)
````
when I'm running the agent.   

I'll stack from scratch and follow exactly your setup (but in my cluster, not minikube).  I'll post the results later.

thanks
