### ISSUE TITLE
Enhancement : Agent for Kaniko

### ISSUE THREAD

**Issue by survivant** [markyjackson-taulia/jenkinsci-on-kubernetes#51]
maybe a example with how to setup a helloworld Dockerfile with the inbound-agent  
and how do to the same thing with Kaniko instead  .

Context : 
I'm trying to setup a CICD on premise using Jenkins.  Feature needed are docker build, helm, gitops (with PR and merge).

**Comment by markyjackson-taulia** [comment]
I will unpack this for you later this week.
I am enjoying you testing these things!

**Comment by markyjackson-taulia** [comment]
@survivant this issue will take me a little more time. I am dedicating more time to mental health away from oss.

**Comment by markyjackson-taulia** [comment]
Closed on accident

**Comment by survivant** [comment]
>  am dedicating more time to mental health away from oss

@markyjackson-taulia I cna understand that.  I'm passing to much time on OSS myself.  Can you tell me what Update #53 is ?

thanks
